const DUPLICATE_KEY_ERROR = 11000;
const FST_JWT_AUTHORIZATION_TOKEN_INVALID = 'FST_JWT_AUTHORIZATION_TOKEN_INVALID';
const FST_JWT_AUTHORIZATION_TOKEN_EXPIRED = 'FST_JWT_AUTHORIZATION_TOKEN_EXPIRED';


module.exports = { DUPLICATE_KEY_ERROR, FST_JWT_AUTHORIZATION_TOKEN_INVALID, FST_JWT_AUTHORIZATION_TOKEN_EXPIRED };
